# Site settings
title: ROMINA ORTIGALA
description: Diseñadora Gráfica
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ROMINA ORTIGALA
user_description: Hola, soy Diseñadora en busca de nuevos desafios.
user_title: Diseñadora Gráfica.
email: romi.ortigala@gmail.com
linkedin_username: 
github_username:  rominix-2022
behance_username: RomiOrtigala
pdf_username: PDF
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
