# Site settings
title: ROMINA ORTIGALA
description: Diseñadora
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ROMINA ORTIGALA
#user_description: 
user_title: Diseñadora
behance_username: RomiOrtigala
# github_username:  rominix-2022
pdf_username: PDF
linkedin_username: romina-ortigala-55401122a
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
email: romi.ortigala@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
